version: "3.9"
services:
  web:
    build: .
    container_name: web
    command: npm run dev
    ports:
      - "3030:3030"
    volumes:
      - .:/app
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_DBNAME=test
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
  db:
    image: mysql:latest
    container_name: db
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=xxxx
      - MYSQL_PASSWORD=xxxx
      - MYSQL_ROOT_PASSWORD=root
volumes:
  mysql_db:
